//
//  AddRouter.swift
//  TodoVipApp
//
//  Created by song on 2023/04/03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddRoutingLogic
{
  func dismiss()
}

protocol AddDataPassing
{
  var dataStore: AddDataStore? { get }
}

class AddRouter: NSObject, AddRoutingLogic, AddDataPassing
{
  weak var viewController: AddViewController?
  var dataStore: AddDataStore?
  
  // MARK: Routing
  
  func dismiss()
  {
    dismissModal(source: viewController!)
  }

  // MARK: Navigation
  
  func dismissModal(source: AddViewController)
  {
    source.dismiss(animated: true)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AddDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
