//
//  ModifyPresenterTests.swift
//  TodoVipApp
//
//  Created by song on 2023/05/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TodoVipApp
import XCTest

class ModifyPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ModifyPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupModifyPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupModifyPresenter()
  {
    sut = ModifyPresenter()
  }
  
  // MARK: Test doubles
  
  class ModifyDisplayLogicSpy: ModifyDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Modify.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = ModifyDisplayLogicSpy()
    sut.viewController = spy
    let response = Modify.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
