//
//  DetailModels.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
  // MARK: Use cases
  
  enum ModifyTodo
  {
    struct Request
    {
      var id: Int
      var title: String
      var isDone: Bool
    }
    struct Response
    {
      var error: Error?
    }
    struct ViewModel
    {
      var error: NetworkError?
    }
  }
  
  enum PresentTodo
  {
    struct Request
    {
    }
    struct Response
    {
      var todo: TodoDataDTO?
      var error: Error?
    }
    struct ViewModel // 프리젠터가 뷰에 전달하는 데이터
    {
      struct DisplayedTodo {
        let id: Int
        let title: String
        let isDone: Bool
        
        init(todo: TodoDTO ) {
          self.id = todo.id
          self.title = todo.title
          self.isDone = todo.isDone
        }
        
      }
      var error: NetworkError?
      var displayedTodo: DisplayedTodo
    }
  }
}
