//
//  DetailInteractor.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func fetchTodo(request: Detail.PresentTodo.Request)
  func modifyTodo(request: Detail.ModifyTodo.Request)
}

protocol DetailDataStore
{
  var todoId: Int? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  
  var todoId: Int?
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?
  
  // MARK: Do something
  
  func fetchTodo(request: Detail.PresentTodo.Request)
  {
    worker = DetailWorker()
    Task {
      guard let todoDataDTO = try await worker?.todoUsecase.fetchTodo(id: todoId ?? 0) else { return }
      let todo = todoDataDTO.data
      let response = Detail.PresentTodo.Response(todo: todo)
      presenter?.presentTodo(response: response)
    }
    
  }
  
  func modifyTodo(request: Detail.ModifyTodo.Request) {
    worker = DetailWorker()
    Task {
      try await worker?.modifyTodo(id: request.id, title: request.title, isDone: request.isDone)
    }
  }
}
