//
//  DetailWorker.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker: TodoWorkerUsecase
{
  var apiManager: TodoApiManager
  
  init(apiManager: TodoApiManager = TodoApiManager(session: URLSession.shared)) {
    self.apiManager = apiManager
  }
  
  func modifyTodo(id: Int, title: String, isDone: Bool) async throws -> TodoEntity
  {
    try await todoUsecase.modifyTodo(id: id, title: title, isDone: isDone)
  }
  
  func fetchtodo(id: Int) async throws -> TodoEntity {
    try await todoUsecase.fetchTodo(id: id)
  }
}
