//
//  DetailWorker.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker: TodoWorkerUsecase
{
  func modifyTodo(id: Int, title: String, isDone: Bool) async throws
  {
    try await todoUsecase.modifyTodo(id: id, title: title, isDone: isDone)
  }
  
  func fetchtodo(id: Int) async throws -> TodoDataDTO {
    try await todoUsecase.fetchTodo(id: id)
  }
}
