//
//  DetailPresenter.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentTodo(response: Detail.PresentTodo.Response)
  func presentModifyResult(response: Detail.ModifyTodo.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentTodo(response: Detail.PresentTodo.Response)
  {
    typealias Todo = Detail.PresentTodo.ViewModel.DisplayedTodo
    
    guard let todo = response.todo?.data else {
      return
    }
    
    let displayTodo = Todo(todo: todo)
    let viewModel = Detail.PresentTodo.ViewModel(error: response.error as? NetworkError, displayedTodo: displayTodo)
    viewController?.displaySomething(viewModel: viewModel)
  }
  
  func presentModifyResult(response: Detail.ModifyTodo.Response) {
     
    let viewModel = Detail.ModifyTodo.ViewModel(error: response.error as? NetworkError)
    viewController?.displayModifyResult(viewmodel: viewModel)
  }
}
