//
//  AddInteractorTests.swift
//  TodoVipApp
//
//  Created by song on 2023/05/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TodoVipApp
import XCTest

class AddInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: AddInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupAddInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupAddInteractor()
  {
    sut = AddInteractor()
  }
  
  // MARK: Test doubles
  
  class AddPresentationLogicSpy: AddPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: Add.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = AddPresentationLogicSpy()
    sut.presenter = spy
    let request = Add.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
