//
//  AddInteractor.swift
//  TodoVipApp
//
//  Created by song on 2023/04/03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddBusinessLogic
{
  func postTodo(request: Add.PostTodo.Request)
}

protocol AddDataStore
{
  //var name: String { get set }
}

class AddInteractor: AddBusinessLogic, AddDataStore
{
  var presenter: AddPresentationLogic?
  var worker: AddWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func postTodo(request: Add.PostTodo.Request)
  {
    worker = AddWorker()
    Task {
      do {
        try await worker?.postTodo(todo: request.todo)
        let response = Add.PostTodo.Response()
        presenter?.cleanAddView(response: response)
      } catch {
        let response = Add.PostTodo.Response(error: error)
        presenter?.cleanAddView(response: response)
      }
    }
  }
}
