//
//  AddPresenter.swift
//  TodoVipApp
//
//  Created by song on 2023/04/03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPresentationLogic
{
  func cleanAddView(response: Add.PostTodo.Response)
}

class AddPresenter: AddPresentationLogic
{
  weak var viewController: AddDisplayLogic?
  
  // MARK: Do something
  
  func cleanAddView(response: Add.PostTodo.Response)
  {
    let viewModel = Add.PostTodo.ViewModel(error: response.error as? NetworkError)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
