//
//  AddViewController.swift
//  TodoVipApp
//
//  Created by song on 2023/04/03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddDisplayLogic: AnyObject
{
  func displaySomething(viewModel: Add.PostTodo.ViewModel)
}

class AddViewController: UIViewController, AddDisplayLogic, Alertable
{
  var interactor: AddBusinessLogic?
  var router: (NSObjectProtocol & AddRoutingLogic & AddDataPassing)?
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = AddInteractor()
    let presenter = AddPresenter()
    let router = AddRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    NotificationCenter.default.post(name: NSNotification.Name("ModalDismissNC"), object: nil, userInfo: nil)
  }
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
  }
  
  // MARK: Do something
  
  @IBOutlet weak var todoLabel: UITextField!
  @IBOutlet weak var isDoneSwitch: UISwitch!
  
  @IBAction func addTodo(_ sender: Any) {
    let request = Add.PostTodo.Request(todo: TodoPostDTO(title: todoLabel.text!, isDone: isDoneSwitch.isOn))
    interactor?.postTodo(request: request)
  }

  func displaySomething(viewModel: Add.PostTodo.ViewModel)
  {
    guard let error = viewModel.error else {
      // 에러 없음
      DispatchQueue.main.async {
        self.todoLabel.text = viewModel.title
        self.isDoneSwitch.isOn = viewModel.isDone
      }
      return
    }
    //에러없음
    DispatchQueue.main.async {
      self.showErrorAlertWithConfirmButton(error.errorDescription ?? "")
    }
  }
}
