////
////  MainWorkerTests.swift
////  TodoVipApp
////
////  Created by song on 2023/04/11.
////  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import TodoVipApp
//import XCTest
//
//class MainWorkerTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: MainWorker!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupMainWorker()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupMainWorker()
//  {
//    sut = MainWorker()
//  }
//  
//  // MARK: Test doubles
//  
//  // MARK: Tests
//  
//  func testSomething()
//  {
//    // Given
//    
//    // When
//    
//    // Then
//  }
//}
