//
//  MainInteractorTests.swift
//  TodoVipApp
//
//  Created by song on 2023/04/11.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TodoVipApp
import XCTest
import Combine

class MainInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MainInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMainInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  var cancellable = Set<AnyCancellable>()
  
  struct MockURLSession: Requestable  {
    func request(_ request: TodoRequestManager) async throws -> Data {
      throw NetworkError.testError
    }
  }
  
  func setupMainInteractor()
  {
    sut = MainInteractor(session: MockURLSession())
  }
  
  // MARK: Test doubles
  
  class MainPresentationLogicSpy: MainPresentationLogic
  {
    @Published var presentTodoListCalled = false
    @Published var presentDeleteTodoCalled = false
    @Published var presentModifyTodoCalled = false
    @Published var presentAddTodoCalled = false

    func presentTodoList(response: TodoListProtocol) {
      presentTodoListCalled = true
    }
    
    func presentDeleteTodo(response: MainScene.DeleteTodo.Response) {
      presentDeleteTodoCalled = true
    }
    
    func presentModifyTodo(response: MainScene.ModifyTodo.Response) {
      presentModifyTodoCalled = true
    }
    
    func presesntAddTodo(response: TodoVipApp.MainScene.AddTodo.Response) {
      presentAddTodoCalled = true
    }
  }
  
  // MARK: Tests
  
  func test_presentTodoList호출되는지() {
    // Given
    let spy = MainPresentationLogicSpy()
    sut.presenter = spy
    let request = MainScene.FetchTodoList.Request()
    
    // When
    sut.fetchTodoList(request: request)
    // Then
    spy.$presentTodoListCalled
      .dropFirst()
      .sink { XCTAssertTrue($0) }
    .store(in: &cancellable)
  }
  
  func test_presentDeleteTodo호출되는지()
  {
    // Given
    let spy = MainPresentationLogicSpy()
    sut.presenter = spy
    let request = MainScene.DeleteTodo.Request(id: 1)

    // When
    sut.deleteTodo(request: request)

    // Then
    spy.$presentDeleteTodoCalled
      .dropFirst()
      .sink { XCTAssertTrue($0) }
    .store(in: &cancellable)
  }

  func test_presentModifyTodo호출되는지()
  {
    // Given
    let spy = MainPresentationLogicSpy()
    sut.presenter = spy
    let request = MainScene.ModifyTodo.Request(id: 0, title: "", isDone: false)

    // When
    sut.modifyTodo(request: request)

    // Then
    spy.$presentModifyTodoCalled
      .dropFirst()
      .sink { XCTAssertTrue($0) }
    .store(in: &cancellable)
  }
}


