//
//  MainViewControllerTests.swift
//  TodoVipApp
//
//  Created by song on 2023/04/11.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TodoVipApp
import XCTest

class MainViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MainViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupMainViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "MainViewController", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "MainViewController") as! MainViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class MainBusinessLogicSpy: MainBusinessLogic
  {
    var fetchTodoListCalled = false
    var deleteTodoCalled = false
    var fetchSearchTodoListCalled = false
    var checkTodoCalled = false
    
    func fetchTodoList(request: MainScene.FetchTodoList.Request) {
      fetchTodoListCalled = true
    }
    func deleteTodo(request: MainScene.DeleteTodo.Request) {
      deleteTodoCalled = true
    }
    func fetchSearchTodoList(request: MainScene.FetchSearchTodoList.Request) {
      fetchSearchTodoListCalled = true
    }
    func checkTodo(request: MainScene.ModifyTodo.Request) {
      checkTodoCalled = true
    }
    
  }
  
  // MARK: Tests
  
  func testShouldDoSomethingWhenViewIsLoaded()
  {
    // Given
    let spy = MainBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.fetchTodoListCalled, "viewDidLoad() should ask the interactor to do something")
  }
  
//  func testDisplaySomething()
//  {
//    // Given
//    let viewModel = Main.Something.ViewModel()
//
//    // When
//    loadView()
//    sut.displaySomething(viewModel: viewModel)
//
//    // Then
//    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
//  }
}
