//
//  MainPresenterTests.swift
//  TodoVipApp
//
//  Created by song on 2023/04/11.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TodoVipApp
import XCTest

class MainPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MainPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMainPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainPresenter()
  {
    sut = MainPresenter()
  }
  
  // MARK: Test doubles
  
  class MainDisplayLogicSpy: MainDisplayLogic
  {
    var displayTodoListCalled = false
    var displayAddTodoCalled = false
    var displayedDeleteTodoCalled = false
    var displayedModifyTodoCalled = false

    func displayTodoList(viewModel: TodoVipApp.MainScene.FetchTodoList.ViewModel) {
      displayTodoListCalled = true
    }
    
    func displayAddTodo(viewModle: TodoVipApp.MainScene.FetchTodoList.ViewModel) {
      displayAddTodoCalled = true
    }
    
    func displayedDeleteTodo(viewModel: TodoVipApp.MainScene.DeleteTodo.ViewModel) {
      displayedDeleteTodoCalled = true
    }
    
    func displayedModifyTodo(viewModel: TodoVipApp.MainScene.ModifyTodo.ViewModel) {
      displayedModifyTodoCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentDisplayTodoList()
  {
    // Given
    let spy = MainDisplayLogicSpy()
    sut.viewController = spy
    let response = MainScene.FetchTodoList.Response(page: 0)
    
    // When
    sut.presentTodoList(response: response)
    
    // Then
    XCTAssertTrue(spy.displayTodoListCalled)
  }
  
  func testDisplayAddTodoTodoList()
  {
    // Given
    let spy = MainDisplayLogicSpy()
    sut.viewController = spy
    let response = MainScene.AddTodo.Response()
    
    // When
    sut.presesntAddTodo(response: response)
    
    // Then
    XCTAssertTrue(spy.displayAddTodoCalled)
  }
  
  func testDisplayedDeleteTodoTodoList()
  {
    // Given
    let spy = MainDisplayLogicSpy()
    sut.viewController = spy
    let response = MainScene.DeleteTodo.Response()
    
    // When
    sut.presentDeleteTodo(response: response)
    
    // Then
    XCTAssertTrue(spy.displayedDeleteTodoCalled)
  }
  
  func testDisplayedModifyTodoTodoList()
  {
    // Given
    let spy = MainDisplayLogicSpy()
    sut.viewController = spy
    let response = MainScene.ModifyTodo.Response()
    
    // When
    sut.presentModifyTodo(response: response)
    
    // Then
    XCTAssertTrue(spy.displayedModifyTodoCalled)
  }
}
