//
//  MainWorker.swift
//  TodoVipApp
//
//  Created by song on 2023/03/24.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker: TodoWorkerUsecase
{
  
  func fetchTodoList(page: Int, perPage: Int) async throws -> [TodoEntity] {
    guard let todoListDTO = try await todoUsecase.fetchTodoList(page: page, perPage: perPage).data else {
      return []
    }
    
    return todoListDTO.map { TodoEntity.init(datunm: $0) }
  }
  
  func deleteTodo(id: Int) async throws {
    try await todoUsecase.deleteTodo(id: id)
  }
  
  func fetchSearchTodoList(page: Int, perPage: Int, query: String) async throws -> [TodoEntity] {
    guard let todoListDTO = try await todoUsecase.fetchSearchTodoList(page: page, perPage: perPage, query: query).data else {
      return []
    }
    
    return todoListDTO.map { TodoEntity.init(datunm: $0) }
  }
}

protocol ApiManagerProtocol {}

protocol TodoWorkerUsecase: ApiManagerProtocol {}

extension TodoWorkerUsecase {
  var todoStorage: TodoStorage {
    return TodoStorage(todoApiManager: apiManager)
  }
  
  var todoRepository: TodoRepository {
    return TodoRepository(todoStorageable: todoStorage)
  }
  
  var todoUsecase: TodoUsecase {
    return TodoUsecase(todoRepository: todoRepository)
  }
}

extension ApiManagerProtocol {
  var apiManager: TodoApiManager {
    return TodoApiManager(session: URLSession.shared)
  }
}


