//
//  MainInteractor.swift
//  TodoVipApp
//
//  Created by song on 2023/03/24.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
  func fetchList(request: PostList.FetchList.Request)
}

protocol MainDataStore
{
  //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
  var presenter: MainPresentationLogic?
  var worker: MainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  
  // 뷰에서 인터렉터한테 시키는 메서드
  func fetchList(request: PostList.FetchList.Request)
  {
    worker = MainWorker()
    
    //요청값을 넘겨주어야 한다.
    guard let postList = worker?.fethList(count: request.count) else { return }
  
    let response = PostList.FetchList.Response(posts: postList)
    
    presenter?.presentPostList(response: response) //프리젠터로 값을 넘겨준다
  }
}
