//
//  MainWorker.swift
//  TodoVipApp
//
//  Created by song on 2023/03/24.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Fakery

class MainWorker: MainWorkerUsecase
{
  
  func fetchTodoList(page: Int, perPage: Int) async throws -> [TodoEntity] {
    guard let todoListDTO = try await fetchUsecase.fetchTodoList(page: page, perPage: perPage).data else {
      return []
    }
    
    return todoListDTO.map { TodoEntity.init(datunm: $0) }
  }
}

protocol ApiManagerProtocol {}

protocol MainWorkerUsecase: ApiManagerProtocol {}

extension MainWorkerUsecase {
  var fetchStorage: FetchStorage {
    return FetchStorage(todoApiManager: apiManager)
  }
  
  var fetchRepository: FetchRepository {
    return FetchRepository(fetchStorageable: fetchStorage)
  }
  
  var fetchUsecase: FetchUsecase {
    return FetchUsecase(fetchRepository: fetchRepository)
  }
}

extension ApiManagerProtocol {
  var apiManager: TodoApiManager {
    return TodoApiManager(session: URLSession.shared)
  }
}


