//
//  MainWorker.swift
//  TodoVipApp
//
//  Created by song on 2023/03/24.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Fakery

class MainWorker
{
  func fethList(count: Int) -> [Post]//엔티티
  {
    let faker = Faker(locale: "ko")
    
    var postList: [Post] = []
    for _ in 0..<count {
      postList.append(Post(title: faker.company.name(), content: faker.lorem.paragraphs(amount: 10)))
    }
    
    return postList
  }
}
