//
//  MainViewController.swift
//  TodoVipApp
//
//  Created by song on 2023/03/24.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Combine
import CombineCocoa

protocol MainDisplayLogic: AnyObject
{
  func displayTodoList(viewModel: MainScene.FetchTodoList.ViewModel)
  func displayDeleteTodo(viewModel: MainScene.DeleteTodo.ViewModel)
  func modifyTodo(viewModel: MainScene.ModifyTodo.ViewModel)
}

class MainViewController: UIViewController, MainDisplayLogic, Alertable
{
  
  var interactor: MainBusinessLogic?
  var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
  
  // MARK: - IBoutlets
  
  // MARK: - Properties
  typealias Displayedtodo = MainScene.FetchTodoList.ViewModel.DisplayedTodo
  let refreshControl: UIRefreshControl = UIRefreshControl()
  var sections: [String] = []
  var todoList: [String: [Displayedtodo]] = [:]
  var page = 1
  var cancellables = Set<AnyCancellable>()
  @Published private var searchText = ""
  @Published private var isloadig: Bool = false
  @Published private var fetchingMore = true
  
  lazy var isTableBottom: AnyPublisher<Bool, Never> = myTableView
    .contentOffsetPublisher
    .map { offset -> Bool in
      let height = self.myTableView.frame.size.height
      let contentTOffset = offset.y
      let distanceFromBottom = self.myTableView.contentSize.height - contentTOffset
      return distanceFromBottom - 200 < height
    }
    .eraseToAnyPublisher()
  
  
  // MARK: Object lifecycle
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = MainInteractor()
    let presenter = MainPresenter()
    let router = MainRouter()
    
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  private func configureView() {
    self.view.backgroundColor = UIColor.theme.backgroundColor
    self.searchBar.clipsToBounds = true
    self.searchBar.layer.cornerRadius = 15
    self.searchBar.layer.borderWidth = 1
    self.searchBar.layer.borderColor = UIColor.theme.boardColor?.cgColor
    self.searchBar.addleftimage(image: UIImage.theme.magnifyingglass?.withTintColor(.gray) ?? UIImage())
    
    addButton.setImage(UIImage.theme.largePlusButton, for: .normal)
    
//    NotificationCenter.default.addObserver(
//      self,
//      selector: #selector(self.didDismissDetailNotification(_:)),
//      name: NSNotification.Name("ModalDismissNC"),
//      object: nil
//    )
  }
  
  private func configureTableView()
  {
    let myTableViewCellNib = UINib(nibName: String(describing: MyTableViewCell.self), bundle: nil)
    self.myTableView.register(myTableViewCellNib, forCellReuseIdentifier: "MyTableViewCell")
    self.myTableView.rowHeight = UITableView.automaticDimension
    self.myTableView.estimatedRowHeight = 120
    self.myTableView.delegate = self
    self.myTableView.dataSource = self
    refreshControl.addTarget(self, action: #selector(self.refreshFunction), for: .valueChanged)
    self.myTableView.refreshControl = refreshControl
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    configureTableView()
    fetchTodoList()
    configureView()
    addSubscription()
  }
  
  // MARK: - @IBOutlets
  
  @IBOutlet weak var myTableView: UITableView!
  @IBOutlet weak var addButton: UIButton!
  @IBOutlet weak var searchBar: UITextField!
  
  // MARK: - addSubscriptionn
  
  private func addSubscription() {
    searchBar.textPublisher()
      .sink { [weak self] in self?.searchTodos($0)}
      .store(in: &cancellables)
    
//        Publishers.CombineLatest(isTableBottom, $fetchingMore)
//          .map { $0 == true && $1 == true }
//          .sink { [weak self] in if $0 { self?.fetchTodoList() } }
//          .store(in: &cancellables)
  }
  
  // MARK: 인터랙터에게 보내는 메서드
  
  private func searchTodos(_ todo: String) {
    if todo == "" {
      let request = MainScene.FetchTodoList.Request()
      interactor?.fetchTodoList(request: request)
      
    } else {
      let request = MainScene.FetchSearchTodoList.Request(quary: todo)
      interactor?.fetchSearchTodoList(request: request)
    }
  }
  
  @objc func didDismissDetailNotification(_ notification: Notification) {
    let fetchRequest = MainScene.FetchTodoList.Request()
    self.interactor?.fetchTodoList(request: fetchRequest)
  }
  
  func fetchTodoList() {
    self.fetchingMore = false
    
    let request = MainScene.FetchTodoList.Request(page: page)
    interactor?.fetchTodoList(request: request)
  }
  
  func deleteTodo(id: Int) {
    let deleteRequest = MainScene.DeleteTodo.Request(id: id)
    interactor?.deleteTodo(request: deleteRequest)
  }
  
  func modifyCheckBox(id: Int, title: String, isDone: Bool) {
    
    let request = MainScene.ModifyTodo.Request(id: id, title: title, isDone: isDone)
    interactor?.checkTodo(request: request)
  }
  
  @IBAction func presentModal(_ sender: Any) {
    router?.presentModalAdd()
  }
  
  // MARK: - 프리젠터에서 뷰로 보내진
  
  func displayTodoList(viewModel: MainScene.FetchTodoList.ViewModel) {
    
    guard let error = viewModel.error else {
      // 에러 없음
      self.page = viewModel.page
      self.todoList = viewModel.displayedTodoList
      self.sections = viewModel.sections
       
      self.fetchingMore = true
      
      DispatchQueue.main.async {
        self.myTableView.reloadData()
      }
      return
    }
    // 에러 있음
    
    DispatchQueue.main.async {
      self.showErrorAlertWithConfirmButton(error.errorDescription ?? "")
    }
  }
  
  func displayDeleteTodo(viewModel: MainScene.DeleteTodo.ViewModel) {
    guard let error = viewModel.error else {
      self.page = viewModel.page
      
      guard let indexPath = viewModel.indexPath,
            let sectionIndex = viewModel.indexPath?.section,
            let rowIndex = viewModel.indexPath?.row  else {
        return
      }
      
      let section = sections[sectionIndex]
      self.todoList[section]?.remove(at: rowIndex)
      
      DispatchQueue.main.async {
        self.myTableView.deleteRows(at: [indexPath], with: .automatic)
      }
      return
    }
    
    DispatchQueue.main.async {
      self.showErrorAlertWithConfirmButton(error.errorDescription ?? "")
    }
  }
  
  func modifyTodo(viewModel: MainScene.ModifyTodo.ViewModel) {
    guard let error = viewModel.error else {
      self.page = viewModel.page

      guard let indexPath = viewModel.indexPath,
            let sectionIndex = viewModel.indexPath?.section,
            let rowIndex = viewModel.indexPath?.row else {
        return
      }
      
      self.todoList[sections[sectionIndex]]?[rowIndex] = MainViewController.Displayedtodo(
        id: viewModel.disPlayTodo?.id ?? 0,
        title: viewModel.disPlayTodo?.title ?? "",
        isDone: viewModel.disPlayTodo?.isDone ?? false,
        updatedTime: viewModel.disPlayTodo?.updatedTime ?? "",
        updatedDate: viewModel.disPlayTodo?.updatedDate ?? ""
      )

      DispatchQueue.main.async {
        self.myTableView.reloadRows(at: [indexPath], with: .automatic)
      }
      return
    }
    
    DispatchQueue.main.async {
      self.showErrorAlertWithConfirmButton(error.errorDescription ?? "")
    }
  }
}

// MARK: - TableView

extension MainViewController: UITableViewDelegate
{
  @objc func refreshFunction() {
    let request = MainScene.FetchTodoList.Request()
    interactor?.fetchTodoList(request: request)
    refreshControl.endRefreshing()
  }
  
  func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
    
    let delete = UIContextualAction(style: .destructive, title: "Delete") { [weak self] (_, _, _) in
      
      guard let data = self?.sections[indexPath.section] else { return }
      guard let todos = self?.todoList[data] else { return }
      
      self?.deleteTodo(id: todos[indexPath.row].id)
    }
    
    return UISwipeActionsConfiguration(actions: [delete])
  }
  
  func tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int)
  {
    let header = view as! UITableViewHeaderFooterView
    header.textLabel?.textColor = .black
//    header.textLabel?.font = UIFont.boldSystemFont(ofSize: 30)
  }
}

extension MainViewController: UITableViewDataSource
{
  
  func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    let date = sections[indexPath.section]
    guard let todos = todoList[date] else { return  }
    
    router?.routeToDetail(todoId: todos[indexPath.row].id)
  }
  
  func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
    
    return sections[section]
  }
  
  func numberOfSections(in tableView: UITableView) -> Int {
    return sections.count
  }
  
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    guard let sectionsCount = todoList[sections[section]]?.count else {
      return 0
    }
    return sectionsCount
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    
    guard let cell = myTableView.dequeueReusableCell(withIdentifier: "MyTableViewCell", for: indexPath) as? MyTableViewCell else {
      return UITableViewCell()
    }
    
    let date = sections[indexPath.section]
    guard let todos = todoList[date] else { return cell }
    cell.configureCell(todo: todos[indexPath.row])
    
    cell.onEditAction = { [weak self] clickedTodo in
      let idDone = !clickedTodo.isDone
      self?.modifyCheckBox(id: clickedTodo.id, title: clickedTodo.title, isDone: idDone)
    }
    
    return cell
  }
}

