//
//  DetailPresenter.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentTodo(response: Detail.PresentTodo.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentTodo(response: Detail.PresentTodo.Response)
  {
    typealias todo = Detail.PresentTodo.ViewModel.DisplayedTodo
     
   let displayTodo = todo(
    id: response.todo.id ?? 0,
    title: response.todo.title ?? "",
    isDone: response.todo.isDone ?? false
   )
    
    
    let viewModel = Detail.PresentTodo.ViewModel(displayedTodo: displayTodo )
    viewController?.displaySomething(viewModel: viewModel)
  }
}
