//
//  DetailModels.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
  // MARK: Use cases
  
  enum Todo
  {
    struct Request
    {
      var id : Int
      var todo: String
      var done: Bool
    }
    struct Response
    {
    }
    struct ViewModel
    {
      struct DisplayedTodo: Hashable {
        let id: Int
        let title: String
        let isDone: Bool
      }
      
      var displayedTodoList: [DisplayedTodo]
    }
  }
}
