//
//  DetailViewController.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailDisplayLogic: AnyObject
{
  func displaySomething(viewModel: Detail.PresentTodo.ViewModel)
}

class DetailViewController: UIViewController, DetailDisplayLogic
{
  var interactor: DetailBusinessLogic?
  var router: (NSObjectProtocol & DetailRoutingLogic & DetailDataPassing)?

  
  
  // MARK: - properties
  var id: Int = 0
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = DetailInteractor()
    let presenter = DetailPresenter()
    let router = DetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    NotificationCenter.default.post(name: NSNotification.Name("ModalDismissNC"), object: nil, userInfo: nil)
  }
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    presentTodo()
  }
  
  // MARK: Do something
    
  @IBOutlet weak var doWorkTextField: UITextField!
  @IBOutlet weak var finishSwitch: UISwitch!
  
  func presentTodo()
  {
    let request = Detail.PresentTodo.Request()
    interactor?.presentTodo(request: request)
  }
  
  @IBAction func modifyButtonDidTap(_ sender: Any) {

    let request = Detail.ModifyTodo.Request(
      id: self.id,
      title: doWorkTextField.text ?? "",
      isDone: finishSwitch.isOn)
    
    Task {
      do {
        try await interactor?.modifyTodo(request: request)
      } catch {
        throw NetworkError.unknown
      }
    }
    
    
  }
  
  func displaySomething(viewModel: Detail.PresentTodo.ViewModel)
  {
    self.doWorkTextField.text = viewModel.displayedTodo.title
    self.finishSwitch.isOn = viewModel.displayedTodo.isDone
    self.id = viewModel.displayedTodo.id
  }
}
