//
//  DetailInteractor.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func doSomething(request: Detail.Todo.Request)
  func presentData()
}

protocol DetailDataStore
{
  var todo: TodoEntity { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  func presentData() {
    
  }
  
  var todo: TodoEntity
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?

  init() {
    let datum = Datum(id: nil, title: nil, isDone: nil, createdAt: nil, updatedAt: nil)
    self.todo = TodoEntity(datunm: datum)
  }
  
  // MARK: Do something
  
  func doSomething(request: Detail.Todo.Request)
  {
    worker = DetailWorker()
    worker?.doSomeWork()
    
    let response = Detail.Todo.Response(todo: todo)
    
    presenter?.presentTodo(response: response)
  }
}
