//
//  DetailInteractor.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func presentTodo(request: Detail.PresentTodo.Request)
  func modifyTodo(request: Detail.ModifyTodo.Request) async throws
}

protocol DetailDataStore
{
  var todo: TodoEntity { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  
  var todo: TodoEntity
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker?
  
  init() {
    let datum = Datum(id: nil, title: nil, isDone: nil, updatedAt: nil)
    self.todo = TodoEntity(datunm: datum)
  }
  
  // MARK: Do something
  
  func presentTodo(request: Detail.PresentTodo.Request)
  {
    let response = Detail.PresentTodo.Response(todo: todo)
    presenter?.presentTodo(response: response)
  }
  
  func modifyTodo(request: Detail.ModifyTodo.Request) async throws {
    worker = DetailWorker()
    try await worker?.modifyTodo(id: request.id, title: request.title, isDone: request.isDone)
  }
}
