//
//  DetailRouter.swift
//  TodoVipApp
//
//  Created by song on 2023/04/02.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailRoutingLogic
{
  func dismiss()
}

protocol DetailDataPassing
{
  var dataStore: DetailDataStore? { get }
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing
{
  
  weak var viewController: DetailViewController?
  var dataStore: DetailDataStore?
  
  // MARK: Routing
    
  func dismiss() {
    dismissModal(source: viewController!)
  }

  // MARK: Navigation
  
  func dismissModal(source: DetailViewController)
  {
    source.dismiss(animated: true)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: DetailDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
