//
//  MainWorker.swift
//  TodoVipApp
//
//  Created by song on 2023/03/24.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker: TodoWorkerUsecase
{
  var apiManager: TodoApiManager
  
  init(reauestable: Requestable) {
    self.apiManager = TodoApiManager(session: reauestable)
  }
  
  func fetchTodoList(page: Int, perPage: Int) async throws -> TodoListEntity? {
    try await todoUsecase.fetchTodoList(page: page, perPage: perPage)
  }
  
  func deleteTodo(id: Int) async throws -> TodoEntityData {
    try await todoUsecase.deleteTodo(id: id)
  }
  
  func fetchSearchTodoList(page: Int, perPage: Int, query: String) async throws -> TodoListEntity? {
    try await todoUsecase.fetchSearchTodoList(page: page, perPage: perPage, query: query)
  }
  
  func modifyTodo(id: Int, title: String, isDone: Bool) async throws -> TodoEntityData {
   try await todoUsecase.modifyTodo(id: id, title: title, isDone: isDone)
  }
}
